# Use root/example as user/password credentials
version: "3.1"

services:

  db:
    image: "mysql:8.1.0"
    container_name: "dev_staging_progjog_no_db"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3307:3307"
